### ISSUE TITLE
dts文件为空

### ISSUE THREAD

**Issue by Jeekate** [asdawn/fine3399#1]
readme所述dts和仓库里的fine3399.dts是空文件

**Comment by asdawn** [comment]
https://github.com/cm9vdA/build-linux/blob/master/boot/dts/rockchip/mainline/rk3399-fine3399.dts

暂时可用这个，这边也复制这个了。

”wifi和蓝牙我关了，spi flash和lcd的配置也有，只是注释掉了，代码都在里边“ by 長風掠影

**Comment by Jeekate** [comment]
好的，谢谢
